version: "3.8"
services:
  web1:
    build: ./quote_gen
    container_name: gen
    ports:
      - "5000"
    deploy:
      replicas: 2  
  web2:
    build: ./quote_disp
    container_name: disp
    ports:
      - "5001"
    depends_on:
      - web1
    deploy:
      replicas: 2    
